const szinekNevei = [
    { nev: "Absolute Zero", hex: "#0048BA" },
    { nev: "Acid Green", hex: "#B0BF1A" },
    { nev: "AliceBlue", hex: "#F0F8FF" },
    { nev: "Alizarin crimson", hex: "#E32636" },
    { nev: "Amaranth", hex: "#E52B50" },
    { nev: "Amber", hex: "#FFBF00" },
    { nev: "Amethyst", hex: "#9966CC" },
    { nev: "AntiqueWhite", hex: "#FAEBD7" },
    { nev: "Apricot", hex: "#FBCEB1" },
    { nev: "Aqua", hex: "#00FFFF" },
    { nev: "Aquamarine", hex: "#7FFFD4" },
    { nev: "Army Green", hex: "#4B5320" },
    { nev: "Arylide Yellow", hex: "#E9D66B" },
    { nev: "Ash Grey", hex: "#B2BEB5" },
    { nev: "Asparagus", hex: "#87A96B" },
    { nev: "Aureolin", hex: "#FDEE00" },
    { nev: "Azure", hex: "#F0FFFF" },
    { nev: "Baby Blue", hex: "#89CFF0" },
    { nev: "Baby Pink", hex: "#F4C2C2" },
    { nev: "Baker-Miller Pink", hex: "#FF91AF" },
    { nev: "Banana Mania", hex: "#FAE7B5" },
    { nev: "Banana Yellow", hex: "#FFE135" },
    { nev: "Barn Red", hex: "#7C0A02" },
    { nev: "Battleship Gray", hex: "#848482" },
    { nev: "Beaver", hex: "#9F8170" },
    { nev: "Beige", hex: "#F5F5DC" },
    { nev: "Bisque", hex: "#FFE4C4" },
    { nev: "Bistre", hex: "#3D2B1F" },
    { nev: "Bitter Lemon", hex: "#CAE00D" },
    { nev: "Bitter Lime", hex: "#BFFF00" },
    { nev: "Bittersweet", hex: "#FE6F5E" },
    { nev: "Bittersweet Shimmer", hex: "#BF4F51" },
    { nev: "Black", hex: "#000000" },
    { nev: "Black Coffee", hex: "#3B2F2F" },
    { nev: "Black Olive", hex: "#3B3C36" },
    { nev: "Black Shadows", hex: "#BFAFB2" },
    { nev: "BlanchedAlmond", hex: "#FFEBCD" },
    { nev: "Bleu de France", hex: "#318CE7" },
    { nev: "Blond", hex: "#FAF0BE" },
    { nev: "Blue (Pantone)", hex: "#0018A8" },
    { nev: "Blue Bell", hex: "#A2A2D0" },
    { nev: "Blue Green", hex: "#0D98BA" },
    { nev: "Blue", hex: "#0000FF" },
    { nev: "BlueViolet", hex: "#8A2BE2" },
    { nev: "Bole", hex: "#79443B" },
    { nev: "Bone", hex: "#E3DAC9" },
    { nev: "Boysenberry", hex: "#873260" },
    { nev: "Brandeis Blue", hex: "#0070FF" },
    { nev: "Brass", hex: "#B5A642" },
    { nev: "Brick Red", hex: "#CB4154" },
    { nev: "Bright Cerulean", hex: "#1DACD6" },
    { nev: "Bright Green", hex: "#66FF00" },
    { nev: "Bright Lavender", hex: "#BF94E4" },
    { nev: "Bright Lilac", hex: "#D891EF" },
    { nev: "Bright Maroon", hex: "#C32148" },
    { nev: "Bright Navy Blue", hex: "#1974D2" },
    { nev: "Bright Turquoise", hex: "#08E8DE" },
    { nev: "Bright Ube", hex: "#D19FE8" },
    { nev: "Brilliant Rose", hex: "#FF55A3" },
    { nev: "Brink Pink", hex: "#FB607F" },
    { nev: "British Racing Green", hex: "#004225" },
    { nev: "Bronze", hex: "#CD7F32" },
    { nev: "Brown", hex: "#A52A2A" },
    { nev: "Brunswick Green", hex: "#1B4D3E" },
    { nev: "Bubble Gum", hex: "#FFC1CC" },
    { nev: "Buff", hex: "#F0DC82" },
    { nev: "Bulgarian Rose", hex: "#480607" },
    { nev: "Burgundy", hex: "#800020" },
    { nev: "Burlywood", hex: "#DEB887" },
    { nev: "Burnished Brown", hex: "#A17A74" },
    { nev: "Burnt Orange", hex: "#CC5500" },
    { nev: "Burnt Sienna", hex: "#E97451" },
    { nev: "Burnt Umber", hex: "#8A3324" },
    { nev: "Byzantine", hex: "#BD33A4" },
    { nev: "Byzantium", hex: "#702963" },
    { nev: "Cadet Grey", hex: "#91A3B0" },
    { nev: "CadetBlue", hex: "#5F9EA0" },
    { nev: "Cadmium Green", hex: "#006B3C" },
    { nev: "Cadmium Orange", hex: "#ED872D" },
    { nev: "Cadmium Red", hex: "#E30022" },
    { nev: "Cadmium Yellow", hex: "#FFF600" },
    { nev: "Cambridge Blue", hex: "#A3C1AD" },
    { nev: "Camel", hex: "#C19A6B" },
    { nev: "Cameo Pink", hex: "#EFBBCC" },
    { nev: "Camouflage Green", hex: "#78866B" },
    { nev: "Canary", hex: "#FFFF99" },
    { nev: "Canary Yellow", hex: "#FFEF00" },
    { nev: "Candy Apple Red", hex: "#FF0800" },
    { nev: "Candy Pink", hex: "#E4717A" },
    { nev: "Caput Mortuum", hex: "#592720" },
    { nev: "Cardinal", hex: "#C41E3A" },
    { nev: "Caribbean Green", hex: "#00CC99" },
    { nev: "Carmine", hex: "#960018" },
    { nev: "Carmine Pink", hex: "#EB4C42" },
    { nev: "Carnation Pink", hex: "#FFA6C9" },
    { nev: "Carnelian", hex: "#B31B1B" },
    { nev: "Carolina Blue", hex: "#56A0D3" },
    { nev: "Carrot Orange", hex: "#ED9121" },
    { nev: "Castleton Green", hex: "#00563F" },
    { nev: "Cedar Chest", hex: "#C95A49" },
    { nev: "Celadon", hex: "#ACE1AF" },
    { nev: "Celadon Green", hex: "#2F847C" },
    { nev: "Celeste", hex: "#B2FFFF" },
    { nev: "Celtic Blue", hex: "#246BCE" },
    { nev: "Cerise", hex: "#DE3163" },
    { nev: "Cerulean", hex: "#007BA7" },
    { nev: "Cerulean Blue", hex: "#2a52BE" },
    { nev: "Cerulean Frost", hex: "#6D9BC3" },
    { nev: "Cg Blue", hex: "#007AA5" },
    { nev: "Chamoisee", hex: "#A0785A" },
    { nev: "Champagne", hex: "#F7E7CE" },
    { nev: "Charcoal", hex: "#36454F" },
    { nev: "Chartreuse", hex: "#7FFF00" },
    { nev: "Cherry Blossom Pink", hex: "#FFB7C5" },
    { nev: "Chestnut", hex: "#954535" },
    { nev: "Chocolate", hex: "#D2691E" },
    { nev: "Chrome Yellow", hex: "#FFA700" },
    { nev: "Cinereous", hex: "#98817B" },
    { nev: "Cinnabar", hex: "#E34234" },
    { nev: "Citrine", hex: "#E4d00A" },
    { nev: "Citron", hex: "#9FA91F" },
    { nev: "Claret", hex: "#7F1734" },
    { nev: "Cobalt", hex: "#0047AB" },
    { nev: "Coffee", hex: "#6F4E37" },
    { nev: "Cool Grey", hex: "#8C92AC" },
    { nev: "Copper", hex: "#B87333" },
    { nev: "Copper Red", hex: "#CB6D51" },
    { nev: "Copper Rose", hex: "#996666" },
    { nev: "Coquelicot", hex: "#FF3800" },
    { nev: "Coral", hex: "#FF7F50" },
    { nev: "Coral Pink", hex: "#F88379" },
    { nev: "Coral", hex: "#FF7256" },
    { nev: "Cordovan", hex: "#893F45" },
    { nev: "Corn", hex: "#FBEC5D" },
    { nev: "CornflowerBlue", hex: "#6495ED" },
    { nev: "Cornsilk", hex: "#FFF8DC" },
    { nev: "Cosmic Cobalt", hex: "#2E2D88" },
    { nev: "Cosmic Latte", hex: "#FFF8E7" },
    { nev: "Cotton Candy", hex: "#FFBCD9" },
    { nev: "Cream", hex: "#FFFDD0" },
    { nev: "Crimson", hex: "#DC143C" },
    { nev: "Crystal", hex: "#A7D8DE" },
    { nev: "Cyan", hex: "#00FFFF" },
    { nev: "Cyclamen", hex: "#F56FA1" },
    { nev: "Daffodil", hex: "#FFFF31" },
    { nev: "Dandelion", hex: "#F0E130" },
    { nev: "Dark Brown", hex: "#654321" },
    { nev: "Dark Byzantium", hex: "#5D3954" },
    { nev: "Dark Jungle Green", hex: "#1A2421" },
    { nev: "Dark Lavender", hex: "#734f96" },
    { nev: "Dark Moss Green", hex: "#4A5D23" },
    { nev: "Dark Pastel Green", hex: "#03C03C" },
    { nev: "Dark Sienna", hex: "#3C1414" },
    { nev: "Dark Sky Blue", hex: "#8CBED6" },
    { nev: "Dark Spring Green", hex: "#177245" },
    { nev: "DarkGoldenrod", hex: "#B8860B" },
    { nev: "DarkGreen", hex: "#006400" },
    { nev: "DarkKhaki", hex: "#BDB76B" },
    { nev: "DarkOliveGreen", hex: "#556B2F" },
    { nev: "DarkOrange", hex: "#FF8C00" },
    { nev: "DarkOrchid", hex: "#9932CC" },
    { nev: "DarkSalmon", hex: "#E9967A" },
    { nev: "DarkSeaGreen", hex: "#8FBC8F" },
    { nev: "DarkSlateBlue", hex: "#483d8B" },
    { nev: "DarkSlateGray", hex: "#2F4F4F" },
    { nev: "DarkTurquoise", hex: "#00CED1" },
    { nev: "DarkViolet", hex: "#9400D3" },
    { nev: "Dartmouth Green", hex: "#00703C" },
    { nev: "Deep Cerise", hex: "#DA3287" },
    { nev: "Deep Champagne", hex: "#FAD6A5" },
    { nev: "Deep Fuchsia", hex: "#C154C1" },
    { nev: "Deep Jungle Green", hex: "#004B49" },
    { nev: "Deep Peach", hex: "#FFCBA4" },
    { nev: "Deep Saffron", hex: "#FF9933" },
    { nev: "Deep Space Sparkle", hex: "#4A646C" },
    { nev: "Deep chestnut", hex: "#B94E48" },
    { nev: "DeepPink", hex: "#FF1493" },
    { nev: "DeepSkyBlue", hex: "#00BFFF" },
    { nev: "Denim", hex: "#1560BD" },
    { nev: "Denim Blue", hex: "#2243B6" },
    { nev: "Desert Sand", hex: "#EDC9AF" },
    { nev: "DimGray", hex: "#696969" },
    { nev: "DodgerBlue", hex: "#1E90FF" },
    { nev: "Dogwood Rose", hex: "#D71868" },
    { nev: "Dutch White", hex: "#EFDFBB" },
    { nev: "Earth Yellow", hex: "#E1A95F" },
    { nev: "Ebony", hex: "#555D50" },
    { nev: "Eggplant", hex: "#614051" },
    { nev: "Eggshell", hex: "#F0EAD6" },
    { nev: "Egyptian Blue", hex: "#1034A6" },
    { nev: "Electric Blue", hex: "#7DF9FF" },
    { nev: "Electric Indigo", hex: "#6F00FF" },
    { nev: "Electric Lime", hex: "#CCFF00" },
    { nev: "Electric Purple", hex: "#BF00FF" },
    { nev: "Emerald", hex: "#50C878" },
    { nev: "Eminence", hex: "#6C3082" },
    { nev: "Eton Blue", hex: "#96C8A2" },
    { nev: "Falu Red", hex: "#801818" },
    { nev: "Fawn", hex: "#E5AA70" },
    { nev: "Feldgrau", hex: "#4D5D53" },
    { nev: "Fern Green", hex: "#4F7942" },
    { nev: "Ferrari Red", hex: "#FF2800" },
    { nev: "Fire Opal", hex: "#E95C4B" },
    { nev: "Firebrick", hex: "#B22222" },
    { nev: "Flamingo Pink", hex: "#FC8eEAC" },
    { nev: "FloralWhite", hex: "#FFFAF0" },
    { nev: "Flourescent Blue", hex: "#15F4EE" },
    { nev: "Forest Green", hex: "#228B22" },
    { nev: "ForestGreen", hex: "#228B22" },
    { nev: "French Beige", hex: "#A67B5B" },
    { nev: "French Bistre", hex: "#856D4D" },
    { nev: "French Blue", hex: "#0072BB" },
    { nev: "French Lilac", hex: "#86608E" },
    { nev: "French Mauve", hex: "#D473D4" },
    { nev: "French Pink", hex: "#FD6C9E" },
    { nev: "French Rose", hex: "#F64A8A" },
    { nev: "French Sky Blue", hex: "#77B5FE" },
    { nev: "French Violet", hex: "#8806CE" },
    { nev: "Frostbite", hex: "#E936A7" },
    { nev: "Fuchsia Purple", hex: "#CC397B" },
    { nev: "Fuchsia Rose", hex: "#C74375" },
    { nev: "Fulvous", hex: "#E48400" },
    { nev: "Fuzzy Wuzzy", hex: "#87421F" },
    { nev: "GO Green", hex: "#00AB66" },
    { nev: "Gainsboro", hex: "#DCDCDC" },
    { nev: "Gamboge", hex: "#E49b0F" },
    { nev: "Generic Viridian", hex: "#007F66" },
    { nev: "GhostWhite", hex: "#F8F8FF" },
    { nev: "Ginger", hex: "#B06500" },
    { nev: "Glaucous", hex: "#6082B6" },
    { nev: "Glossy Grape", hex: "#AB92B3" },
    { nev: "Gold Fusion", hex: "#85754E" },
    { nev: "Gold", hex: "#FFD700" },
    { nev: "Golden Brown", hex: "#996515" },
    { nev: "Golden Poppy", hex: "#FCC200" },
    { nev: "Golden Yellow", hex: "#FFDF00" },
    { nev: "Goldenrod", hex: "#DAA520" },
    { nev: "Goldenrod", hex: "#FFC125" },
    { nev: "Granite Gray", hex: "#676767" },
    { nev: "Granny Smith Apple", hex: "#A8E4A0" },
    { nev: "Gray", hex: "#BEBEBE" },
    { nev: "Green (Crayola)", hex: "#1CAC78" },
    { nev: "Green (Pantone)", hex: "#00AD43" },
    { nev: "Green (Pigment)", hex: "#00A550" },
    { nev: "Green Lizard", hex: "#A7F432" },
    { nev: "Green Sheen", hex: "#6EAEA1" },
    { nev: "Green", hex: "#00FF00" },
    { nev: "GreenYellow", hex: "#ADFF2F" },
    { nev: "Grullo", hex: "#A99A86" },
    { nev: "Gunmetal", hex: "#2A3439" },
    { nev: "Han Blue", hex: "#446CCF" },
    { nev: "Han Purple", hex: "#5218FA" },
    { nev: "Harlequin", hex: "#3FFF00" },
    { nev: "Harvest Gold", hex: "#DA9100" },
    { nev: "Heliotrope", hex: "#DF73FF" },
    { nev: "Hollywood Cerise", hex: "#F400A1" },
    { nev: "Honeydew", hex: "#F0FFF0" },
    { nev: "Honolulu Blue", hex: "#006BD0" },
    { nev: "Hot Magenta", hex: "#FF1DCE" },
    { nev: "HotPink", hex: "#FF69B4" },
    { nev: "Hunter Green", hex: "#355E3B" },
    { nev: "Iceberg", hex: "#71A6D2" },
    { nev: "Icterine", hex: "#FCF75E" },
    { nev: "Illuminating Emerald", hex: "#319177" },
    { nev: "Imperial Red", hex: "#ED2939" },
    { nev: "Inchworm", hex: "#B2EC5D" },
    { nev: "India Green", hex: "#138808" },
    { nev: "Indian Yellow", hex: "#E3A857" },
    { nev: "IndianRed", hex: "#CD5C5C" },
    { nev: "Indigo", hex: "#4B0082" },
    { nev: "International Orange", hex: "#FF4F00" },
    { nev: "Iris", hex: "#5A4FCF" },
    { nev: "Isabelline", hex: "#F4F0EC" },
    { nev: "Ivory", hex: "#FFFFF0" },
    { nev: "Jade", hex: "#00A86B" },
    { nev: "Japanese Carmine", hex: "#9D2933" },
    { nev: "Jasmine", hex: "#F8DE7E" },
    { nev: "Jazzberry Jam", hex: "#A50B5E" },
    { nev: "Jonquil", hex: "#F4CA16" },
    { nev: "Jungle Green", hex: "#29AB87" },
    { nev: "Kelly Green", hex: "#4CBB17" },
    { nev: "Keppel", hex: "#3AB09E" },
    { nev: "Key Lime", hex: "#E8F48C" },
    { nev: "Khaki", hex: "#F0E68C" },
    { nev: "Kombu Green", hex: "#354230" },
    { nev: "Languid Lavender", hex: "#D6CADD" },
    { nev: "Lapis Lazuli", hex: "#26619C" },
    { nev: "Laser Lemon", hex: "#FFFF66" },
    { nev: "Laurel Green", hex: "#A9BA9D" },
    { nev: "Lavender", hex: "#E6E6FA" },
    { nev: "Lavender (Floral)", hex: "#B57EDC" },
    { nev: "Lavender Blue", hex: "#CCCCFF" },
    { nev: "Lavender Gray", hex: "#C4C3D0" },
    { nev: "LavenderBlush", hex: "#FFF0F5" },
    { nev: "LawnGreen", hex: "#7CFC00" },
    { nev: "Lemon", hex: "#FFF700" },
    { nev: "Lemon Curry", hex: "#CCA01D" },
    { nev: "Lemon Glacier", hex: "#FDFF00" },
    { nev: "Lemon Meringue", hex: "#F6EABE" },
    { nev: "Lemon Yellow", hex: "#FFF44F" },
    { nev: "LemonChiffon", hex: "#FFFACD" },
    { nev: "Light", hex: "#EEDD82" },
    { nev: "Light Cornflower Blue", hex: "#93CCEA" },
    { nev: "Light French Beige", hex: "#C8AD7F" },
    { nev: "Light Orange", hex: "#FED8B1" },
    { nev: "Light Periwinkle", hex: "#C5CBE1" },
    { nev: "LightBlue", hex: "#ADD8E6" },
    { nev: "LightCoral", hex: "#F08080" },
    { nev: "LightCyan", hex: "#E0FFFF" },
    { nev: "LightGoldenrod", hex: "#FFEC8b" },
    { nev: "LightGoldenrodYellow", hex: "#FAFAD2" },
    { nev: "LightGray", hex: "#D3D3D3" },
    { nev: "LightPink", hex: "#FFB6C1" },
    { nev: "LightSalmon", hex: "#FFA07A" },
    { nev: "LightSeaGreen", hex: "#20B2AA" },
    { nev: "LightSkyBlue", hex: "#87CEFA" },
    { nev: "LightSlateBlue", hex: "#8470FF" },
    { nev: "LightSlateGray", hex: "#778899" },
    { nev: "LightSteelBlue", hex: "#B0C4DE" },
    { nev: "LightYellow", hex: "#FFFFE0" },
    { nev: "Lilac", hex: "#C8A2C8" },
    { nev: "Lilac Luster", hex: "#AE98AA" },
    { nev: "LimeGreen", hex: "#32CD32" },
    { nev: "Lincoln Green", hex: "#195905" },
    { nev: "Linen", hex: "#FAF0E6" },
    { nev: "Little Boy Blue", hex: "#6CA0DC" },
    { nev: "MSU Green", hex: "#18453B" },
    { nev: "Macaroni and Cheese", hex: "#FFBD88" },
    { nev: "Madder Lake", hex: "#CC3336" },
    { nev: "Magenta", hex: "#FF00FF" },
    { nev: "Magenta (Crayola)", hex: "#F653A6" },
    { nev: "Magenta (Pantone)", hex: "#D0417E" },
    { nev: "Magenta Haze", hex: "#9F4576" },
    { nev: "Magic Mint", hex: "#AAF0D1" },
    { nev: "Mahogany", hex: "#C04000" },
    { nev: "Majorelle Blue", hex: "#6050DC" },
    { nev: "Malachite", hex: "#0BDA51" },
    { nev: "Manatee", hex: "#979AAA" },
    { nev: "Mandarin", hex: "#F37A48" },
    { nev: "Mango", hex: "#FDBE02" },
    { nev: "Mango Tango", hex: "#FF8243" },
    { nev: "Mantis", hex: "#74C365" },
    { nev: "Marigold", hex: "#EAA221" },
    { nev: "Maroon", hex: "#B03060" },
    { nev: "Mauve", hex: "#E0B0FF" },
    { nev: "Mauve Taupe", hex: "#915F6D" },
    { nev: "Mauvelous", hex: "#EF98AA" },
    { nev: "Maximum Blue Green", hex: "#30BFBF" },
    { nev: "Maximum Blue Purple", hex: "#ACACE6" },
    { nev: "Maximum Green", hex: "#5E8C31" },
    { nev: "Maxmum Blue", hex: "#47ABCC" },
    { nev: "May Green", hex: "#4C9141" },
    { nev: "Maya Blue", hex: "#73C2FB" },
    { nev: "Medium", hex: "#66CDAA" },
    { nev: "Medium Aquamarine", hex: "#66DDAA" },
    { nev: "Medium Candy Apple Red", hex: "#E2062C" },
    { nev: "Medium Carmine", hex: "#AF4035" },
    { nev: "Medium Champagne", hex: "#F3e5AB" },
    { nev: "MediumAquamarine", hex: "#66CDAA" },
    { nev: "MediumBlue", hex: "#0000CD" },
    { nev: "MediumOrchid", hex: "#BA55D3" },
    { nev: "MediumPurple", hex: "#9370DB" },
    { nev: "MediumSeaGreen", hex: "#3CB371" },
    { nev: "MediumSlateBlue", hex: "#7B68EE" },
    { nev: "MediumSpringGreen", hex: "#00FA9A" },
    { nev: "MediumTurquoise", hex: "#48D1CC" },
    { nev: "MediumVioletRed", hex: "#C71585" },
    { nev: "Mellow Apricot", hex: "#F8B878" },
    { nev: "Melon", hex: "#FEBAAD" },
    { nev: "Metallic Gold", hex: "#D3AF37" },
    { nev: "Metallic Seaweed", hex: "#0A7E8C" },
    { nev: "Metallic Sunburst", hex: "#9C7C38" },
    { nev: "Mexican Pink", hex: "#E4007C" },
    { nev: "Middle Blue", hex: "#7ED4E6" },
    { nev: "Middle Blue Green", hex: "#8DD9CC" },
    { nev: "Middle Blue Purple", hex: "#8B72BE" },
    { nev: "Middle Green", hex: "#4D8C57" },
    { nev: "Middle Green Yellow", hex: "#ACBF60" },
    { nev: "Middle Grey", hex: "#8B8680" },
    { nev: "Middle Purple", hex: "#D982B5" },
    { nev: "Middle Red", hex: "#E58E73" },
    { nev: "Middle Red Purple", hex: "#A55353" },
    { nev: "Middle Yellow", hex: "#FFEB00" },
    { nev: "Middle Yellow Red", hex: "#ECB176" },
    { nev: "Midnight Green", hex: "#004953" },
    { nev: "MidnightBlue", hex: "#191970" },
    { nev: "Mikado Yellow", hex: "#FFC40C" },
    { nev: "Mimi Pink", hex: "#FFDAE9" },
    { nev: "Mindaro", hex: "#E3F988" },
    { nev: "Minion Yellow", hex: "#F5E050" },
    { nev: "Mint", hex: "#3EB489" },
    { nev: "Mint Green", hex: "#98FF98" },
    { nev: "MintCream", hex: "#F5FFFA" },
    { nev: "Misty Moss", hex: "#BBB477" },
    { nev: "MistyRose", hex: "#FFE4E1" },
    { nev: "Moccasin", hex: "#FFE4B5" },
    { nev: "Mode Beige", hex: "#967117" },
    { nev: "Moss Green", hex: "#8A9A5B" },
    { nev: "Mountain Meadow", hex: "#30BA8F" },
    { nev: "Mountbatten Pink", hex: "#997A8D" },
    { nev: "Mulberry", hex: "#C54b8C" },
    { nev: "Mustard", hex: "#FFDB58" },
    { nev: "Myrtle Green", hex: "#317873" },
    { nev: "Mystic Maroon", hex: "#AD4379" },
    { nev: "Nadeshiko Pink", hex: "#F6ADC6" },
    { nev: "NavajoWhite", hex: "#FFDEAD" },
    { nev: "NavyBlue", hex: "#000080" },
    { nev: "Neon Blue", hex: "#4666FF" },
    { nev: "Neon Carrot", hex: "#FFA343" },
    { nev: "Neon Fuchsia", hex: "#FE4164" },
    { nev: "Neon Green", hex: "#39FF14" },
    { nev: "Nickel", hex: "#727472" },
    { nev: "Nyanza", hex: "#e9FFDB" },
    { nev: "Ocean Blue", hex: "#4F42B5" },
    { nev: "Ocean Green", hex: "#48BF91" },
    { nev: "Ochre", hex: "#CC7722" },
    { nev: "Old Burgundy", hex: "#43302E" },
    { nev: "Old Gold", hex: "#CFB53B" },
    { nev: "Old Lavender", hex: "#796878" },
    { nev: "Old Mauve", hex: "#673147" },
    { nev: "Old Rose", hex: "#C08081" },
    { nev: "OldLace", hex: "#FDF5E6" },
    { nev: "Olive", hex: "#808000" },
    { nev: "Olive Green", hex: "#5B35C" },
    { nev: "OliveDrab", hex: "#6B8E23" },
    { nev: "Olivine", hex: "#9AB973" },
    { nev: "Opal", hex: "#A8C3BC" },
    { nev: "Opera Maue", hex: "#B784a7" },
    { nev: "Orange (Crayola)", hex: "#FF5800" },
    { nev: "Orange Peel", hex: "#FF9F00" },
    { nev: "Orange Soda", hex: "#FA5B3D" },
    { nev: "Orange", hex: "#FFA500" },
    { nev: "OrangeRed", hex: "#FF4500" },
    { nev: "Orchid", hex: "#DA70D6" },
    { nev: "Orchid (Crayola)", hex: "#E29CD2" },
    { nev: "Orchid Pink", hex: "#F2BDCD" },
    { nev: "Orchid", hex: "#FF83FA" },
    { nev: "Outrageous Orange", hex: "#FF6E4A" },
    { nev: "Oxblood", hex: "#4A0000" },
    { nev: "Oxford Blue", hex: "#002147" },
    { nev: "Pacific Blue", hex: "#1CA9C9" },
    { nev: "Palatinate Purple", hex: "#682860" },
    { nev: "Pale", hex: "#DB7093" },
    { nev: "Pale Aqua", hex: "#BCD4E6" },
    { nev: "Pale Cerulean", hex: "#9BC4E2" },
    { nev: "Pale Pink", hex: "#FADADD" },
    { nev: "Pale Silver", hex: "#C9C0BB" },
    { nev: "Pale Spring Bud", hex: "#ECEBBD" },
    { nev: "PaleGoldenrod", hex: "#EEE8AA" },
    { nev: "PaleGreen", hex: "#98FB98" },
    { nev: "PaleTurquoise", hex: "#AFEEEE" },
    { nev: "PaleVioletRed", hex: "#DB7093" },
    { nev: "Pansy Purple", hex: "#78184A" },
    { nev: "PapayaWhip", hex: "#FFEFD5" },
    { nev: "Paradise Pink", hex: "#E63E62" },
    { nev: "Pastel Pink", hex: "#DEA5A4" },
    { nev: "Patriarch (Purple)", hex: "#800080" },
    { nev: "Peach", hex: "#FFE5B4" },
    { nev: "PeachPuff", hex: "#FFDAB9" },
    { nev: "Pear", hex: "#DLE231" },
    { nev: "Pearly Purple", hex: "#B768A2" },
    { nev: "Persian Blue", hex: "#1C39BB" },
    { nev: "Persian Green", hex: "#00A693" },
    { nev: "Persian Indigo", hex: "#32127A" },
    { nev: "Persian Orange", hex: "#D99058" },
    { nev: "Persian Pink", hex: "#F77FBE" },
    { nev: "Persian Plum", hex: "#701C1C" },
    { nev: "Persian Red", hex: "#CC3333" },
    { nev: "Persian Rose", hex: "#FE28A2" },
    { nev: "Pewter Blue", hex: "#8BA8B7" },
    { nev: "Phthalo Blue", hex: "#000F89" },
    { nev: "Phthalo Green", hex: "#123524" },
    { nev: "Pictorial Carmine", hex: "#C30B4E" },
    { nev: "Piggy Pink", hex: "#FDDDE6" },
    { nev: "Pine Green", hex: "#01796F" },
    { nev: "Pine Tree", hex: "#2A2F23" },
    { nev: "Pink", hex: "#FFC0CB" },
    { nev: "Pink (Pantone)", hex: "#D74894" },
    { nev: "Pink Flamingo", hex: "#FC74FD" },
    { nev: "Pink Sherbet", hex: "#F78FA7" },
    { nev: "Pistachio", hex: "#93C572" },
    { nev: "Platinum", hex: "#E5E4E2" },
    { nev: "Plum", hex: "#8E4585" },
    { nev: "Plump Purple", hex: "#5946B2" },
    { nev: "Portland Orange", hex: "#FF5A36" },
    { nev: "PowderBlue", hex: "#B0E0E6" },
    { nev: "Prussian Blue", hex: "#003153" },
    { nev: "Puce", hex: "#CC8899" },
    { nev: "Pumpkin", hex: "#FF7518" },
    { nev: "Purple", hex: "#A020F0" },
    { nev: "Quinacridone Magenta", hex: "#8E3A59" },
    { nev: "Radical Red", hex: "#FF355E" },
    { nev: "Raspberry", hex: "#E30B5D" },
    { nev: "Razzmatazz", hex: "#E3256B" },
    { nev: "Rebeccapurple", hex: "#663399" },
    { nev: "Red Orange", hex: "#FF5349" },
    { nev: "Red", hex: "#FF0000" },
    { nev: "Redwood", hex: "#A45A52" },
    { nev: "Rifle Green", hex: "#444C38" },
    { nev: "Rocket Metallic", hex: "#8A7F80" },
    { nev: "Rose", hex: "#FF007F" },
    { nev: "Rose Bonbon", hex: "#F9429E" },
    { nev: "Rose Dust", hex: "#9E5E6F" },
    { nev: "Rose Pink", hex: "#FF66CC" },
    { nev: "Rose Taupe", hex: "#905D5D" },
    { nev: "Rosewood", hex: "#65000B" },
    { nev: "RosyBrown", hex: "#BC8F8F" },
    { nev: "RoyalBlue", hex: "#4169E1" },
    { nev: "Ruby", hex: "#E0115F" },
    { nev: "Russet", hex: "#80461B" },
    { nev: "Russian Green", hex: "#679267" },
    { nev: "Russian Violet", hex: "#32174D" },
    { nev: "Rust", hex: "#B7410E" },
    { nev: "SaddleBrown", hex: "#8B4513" },
    { nev: "Saffron", hex: "#F4C430" },
    { nev: "Sage", hex: "#BCB88A" },
    { nev: "Salmon", hex: "#FA8072" },
    { nev: "SandyBrown", hex: "#F4A460" },
    { nev: "Sap Green", hex: "#507D2A" },
    { nev: "Sapphire", hex: "#0F52BA" },
    { nev: "Scarlet", hex: "#FF2400" },
    { nev: "School Bus Yellow", hex: "#FFD800" },
    { nev: "SeaGreen", hex: "#54FF9F" },
    { nev: "Seal Brown", hex: "#59260B" },
    { nev: "Seashell", hex: "#FFF5EE" },
    { nev: "Selective Yellow", hex: "#FFBA00" },
    { nev: "Sepia", hex: "#704214" },
    { nev: "Shamrock Green", hex: "#009E60" },
    { nev: "Shocking Pink", hex: "#FC0FC0" },
    { nev: "Sienna", hex: "#A0522D" },
    { nev: "Silver", hex: "#C0C0C0" },
    { nev: "Silver Pink", hex: "#C4AEAD" },
    { nev: "Sinopia", hex: "#CB410B" },
    { nev: "Skobeloff", hex: "#007474" },
    { nev: "SkyBlue", hex: "#87CEEB" },
    { nev: "SlateBlue", hex: "#6A5ACD" },
    { nev: "SlateGray", hex: "#708090" },
    { nev: "Smoky Black", hex: "#100C08" },
    { nev: "Snow", hex: "#FFFAFA" },
    { nev: "Spanish Bistre", hex: "#807532" },
    { nev: "Spanish Orange", hex: "#E86100" },
    { nev: "Spanish Pink", hex: "#F7BFBE" },
    { nev: "Spanish Viridian", hex: "#007F5C" },
    { nev: "Spring Bud", hex: "#A7FC00" },
    { nev: "Spring Frost", hex: "#87FF2A" },
    { nev: "SpringGreen", hex: "#00FF7F" },
    { nev: "Steel Pink", hex: "#CC33CC" },
    { nev: "SteelBlue", hex: "#4682B4" },
    { nev: "Straw", hex: "#E4D96F" },
    { nev: "Sunglow", hex: "#FFCC33" },
    { nev: "Super Pink", hex: "#CF6BA9" },
    { nev: "Sweet Brown", hex: "#A83731" },
    { nev: "Tan", hex: "#D2B48C" },
    { nev: "Tangerine", hex: "#F28500" },
    { nev: "Tart Orange", hex: "#FB4D46" },
    { nev: "Taupe", hex: "#483C32" },
    { nev: "Taupe Gray", hex: "#8B8589" },
    { nev: "Tea Green", hex: "#D0F0C0" },
    { nev: "Teal", hex: "#008080" },
    { nev: "Teal Blue", hex: "#367588" },
    { nev: "Terra Cotta", hex: "#E2725B" },
    { nev: "Thistle", hex: "#D8BFD8" },
    { nev: "Tiffany Blue", hex: "#0ABAB5" },
    { nev: "Timberwolf", hex: "#DBD7D2" },
    { nev: "Titanium Yellow", hex: "#EEE600" },
    { nev: "Tomato", hex: "#FF6347" },
    { nev: "Tropical Rainforest", hex: "#00755E" },
    { nev: "Tumbleweed", hex: "#DEAA88" },
    { nev: "Turquoise", hex: "#40E0D0" },
    { nev: "Turquoise Blue", hex: "#00FFEF" },
    { nev: "Tuscan Red", hex: "#7C4848" },
    { nev: "Tuscany", hex: "#C09999" },
    { nev: "Twilight Lavender", hex: "#8A496B" },
    { nev: "Tyrian Purple", hex: "#66023C" },
    { nev: "UP Forest Green", hex: "#014421" },
    { nev: "UP Maroon", hex: "#7B1113" },
    { nev: "Ultra Pink", hex: "#FF6FFF" },
    { nev: "Ultramarine", hex: "#3F00FF" },
    { nev: "Ultramarine Blue", hex: "#4166F5" },
    { nev: "Unbleached Silk", hex: "#FFDDCA" },
    { nev: "United Nations Blue", hex: "#5B92E5" },
    { nev: "Upsdell Red", hex: "#AE2029" },
    { nev: "Van Dyke Brown", hex: "#664228" },
    { nev: "Vanilla", hex: "#F3E5AB" },
    { nev: "Vanilla Ice", hex: "#F38FA9" },
    { nev: "Vegas Gold", hex: "#C5B358" },
    { nev: "Venetian Red", hex: "#C80815" },
    { nev: "Verdigris", hex: "#43B3AE" },
    { nev: "Vermillion", hex: "#E34234" },
    { nev: "Violet", hex: "#EE82EE" },
    { nev: "VioletRed", hex: "#D02090" },
    { nev: "Viridian", hex: "#40826D" },
    { nev: "Viridian Green", hex: "#009698" },
    { nev: "Vivid Burgundy", hex: "#9F1D35" },
    { nev: "Vivid Sky Blue", hex: "#00CCFF" },
    { nev: "Vivid Tangerine", hex: "#FFA089" },
    { nev: "Vivid Violet", hex: "#9F00FF" },
    { nev: "Volt", hex: "#CEFF00" },
    { nev: "Warm Black", hex: "#004242" },
    { nev: "Wheat", hex: "#F5DEB3" },
    { nev: "White", hex: "#FFFFFF" },
    { nev: "WhiteSmoke", hex: "#F5F5F5" },
    { nev: "Wild Blue Yonder", hex: "#A2ADD0" },
    { nev: "Wild Orchid", hex: "#D470A2" },
    { nev: "Wild Strawberry", hex: "#FF43A4" },
    { nev: "Windsor Tan", hex: "#A75502" },
    { nev: "Wine", hex: "#722F37" },
    { nev: "Wintergreen Dream", hex: "#56887D" },
    { nev: "Wisteria", hex: "#C9A0DC" },
    { nev: "Xanadu", hex: "#738678" },
    { nev: "Yellow Orange", hex: "#FFAE42" },
    { nev: "Yellow Pantone", hex: "#FEDF00" },
    { nev: "Yellow", hex: "#FFFF00" },
    { nev: "YellowGreen", hex: "#9ACD32" },
    { nev: "Zaffre", hex: "#0014A8" },
    { nev: "Zomp", hex: "#39A78E" },
];